# Generated by Django 3.2.3 on 2021-06-01 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='Choose_Your_Destinations',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
